version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: raymanoz/borgy:1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Setup
          command: |
            ./gradlew init_borgy
      - run:
          name: Run tests
          command: |
            ./gradlew test
      - run:
          name: Build the jar
          command: |
            ./gradlew jar
      - store_artifacts:
          path: build/libs
workflows:
  version: 2
  workflow:
    jobs:
      - build