version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
#      - restore_cache:
#          name: Restore Yarn Package Cache
#          keys:
#            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: get node
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | bash
            apt-get install -y nodejs
      - run:
          name: get yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Setup
          command: |
            ./gradlew init_borgy
      - run:
          name: Run tests
          command: |
            ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Build the jar
          command: |
            ./gradlew jar
      - store_artifacts:
          path: build/libs
workflows:
  version: 2
  workflow:
    jobs:
      - build